import { ThemeProvider } from '@/components/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TailwindIndicator } from '@/components/TailwindIndicator'
import { cookies, headers } from 'next/headers'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,
}) {
    const headersList = headers();
    const cookiesList = cookies();

    const url = new URL(headersList.get('x-url') ?? '');

    if (!url.pathname.startsWith('/login') && !cookiesList.get('token')) {
        return redirect('/login')
    }

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} bg-[#181818]`}>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
                        {children}
                </ThemeProvider>
                <TailwindIndicator />
            </body>
        </html>
    )
}
